# permissions for end users to edit des.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: de-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: intervention-go
    app.kubernetes.io/part-of: intervention-go
    app.kubernetes.io/managed-by: kustomize
  name: de-editor-role
rules:
- apiGroups:
  - intervention.xue1.top
  resources:
  - des
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intervention.xue1.top
  resources:
  - des/status
  verbs:
  - get
